# Builds the static app
# Check for error free build and cache artifacts

name: Build
on: push

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
